import { BUTTONS, BUTTON_TYPES } from "../../consts";

export const ORDERED_BUTTONS = [
  { code: BUTTONS.CLEAR, type: BUTTON_TYPES.COMMAND },
  { code: BUTTONS.CLEAR_ELEMENT, type: BUTTON_TYPES.COMMAND },
  { code: BUTTONS.DIVISION, type: BUTTON_TYPES.OPERATION },
  { code: BUTTONS.MULTIPLICATION, type: BUTTON_TYPES.OPERATION },
  {
    code: BUTTONS.OPENING_PARENTHESIS,
    type: BUTTON_TYPES.OPERATION,
    isWide: false,
  },
  {
    code: BUTTONS.CLOSING_PARENTHESIS,
    type: BUTTON_TYPES.OPERATION,
    isWide: false,
  },
  { code: BUTTONS.POTENCY, type: BUTTON_TYPES.OPERATION },
  { code: BUTTONS.SUBTRACTION, type: BUTTON_TYPES.OPERATION },
  { code: BUTTONS.SEVEN, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.EIGHT, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.NINE, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.ADDITION, type: BUTTON_TYPES.OPERATION, isTall: true },
  { code: BUTTONS.FOUR, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.FIVE, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.SIX, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.ONE, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.TWO, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.THREE, type: BUTTON_TYPES.NUMBER },
  { code: BUTTONS.RESULT, type: BUTTON_TYPES.COMMAND, isTall: true },
  { code: BUTTONS.ZERO, type: BUTTON_TYPES.NUMBER, isWide: true },
  { code: BUTTONS.POINT, type: BUTTON_TYPES.NUMBER },
];
